docs: update installation instructions to use new Storybook CLI
nuxt-modules/storybook pull request #659
Opened 2024-06-26 05:14 UTC by tobiasdiez

2024-06-28 06:26 UTC, Ibochkarev commented
@tobiasdiez hello!

In this version of `pnpm dlx storybook@latest init`, the React framework is installed by default — you need to display what changes the user should make after installation

![image](https://github.com/nuxt-modules/storybook/assets/2138260/a3d12c94-0a91-48a0-9ddc-d1e1159298f1)

2024-06-28 10:15 UTC, tobiasdiez commented
Thanks for testing. Did this use the `8.2.0-alpha` version of storybook? The "latest" stable version of storybook cli doesn't yet include support for nuxt.

2024-07-12 11:01 UTC, DamianGlowala requested changes

2024-07-12 11:01 UTC, DamianGlowala commented on docs/content/1.getting-started/1.setup.md
> +The Storybook CLI provides a very convenient way to install Storybook and the Nuxt integration. Run the following command in your project's root directory:
```suggestion
The Storybook CLI provides a convenient way to integrate Storybook with Nuxt. Run the following command in your project's root directory:
```

2024-07-12 11:01 UTC, DamianGlowala commented on docs/content/1.getting-started/1.setup.md
> +This command will install Storybook along with the Nuxt module, set up the necessary scripts to configure Storybook and add some boilerplate stories to get you started.
```suggestion
This command will install Storybook along with the Nuxt module, set up the necessary scripts to configure Storybook, and add some boilerplate stories to get you started.
```

2024-07-12 11:01 UTC, DamianGlowala commented on docs/content/1.getting-started/1.setup.md
> +When you run your Nuxt app in development mode, the Storybook server will automatically start in the background. The url to access Storybook will be displayed in the console (usually `http://localhos
```suggestion
When you run your Nuxt app in development mode, the Storybook server will automatically start in the background. The URL to access Storybook will be displayed in the console (`http://localhost:6006` by default).
```

2024-07-12 11:01 UTC, DamianGlowala commented on docs/content/1.getting-started/1.setup.md
> +When you installed Storybook using the CLI, you will find a few stories in the `components` directory to get you started. You can add your own stories to this directory or create a new directory for
```suggestion
When you install Storybook using the CLI, you will find a few stories in the `components` directory to get you started. You can add your own stories to this directory or create a new directory for your stories (in which case you will need to update the [Storybook configuration](/storybook/config)).
```

2024-07-12 11:01 UTC, DamianGlowala commented on docs/content/1.getting-started/1.setup.md
> +For more information on how to write stories and the next steps, we refer to the [Storybook documentation](https://storybook.js.org/docs/get-started/whats-a-story).
```suggestion
For more information on how to write stories and the next steps, refer to the [Storybook documentation](https://storybook.js.org/docs/get-started/whats-a-story).
```

2024-07-13 14:58 UTC, tobiasdiez commented
Thanks @DamianGlowala for the nice suggestions!

2025-01-16 08:46 UTC, merged